"""alteração tabela produto

Revision ID: 45897e896b0d
Revises: ef52012676f6
Create Date: 2025-07-12 08:09:25.351163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45897e896b0d'
down_revision: Union[str, Sequence[str], None] = 'ef52012676f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('Beneficios', sa.String(), nullable=False))
    op.drop_column('produto', 'Baneficios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('Baneficios', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('produto', 'Beneficios')
    # ### end Alembic commands ###
