"""Criação de role para usuario

Revision ID: 9b751f702042
Revises: 45897e896b0d
Create Date: 2025-07-13 09:47:21.809239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b751f702042'
down_revision: Union[str, Sequence[str], None] = '45897e896b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = sa.Enum('admin', 'user', name='roleenum')
    role_enum.create(op.get_bind())
    op.add_column(
        'users',
        sa.Column('role', role_enum, nullable=False, server_default='user')
    )
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum = sa.Enum('admin', 'user', name='roleenum')
    role_enum.drop(op.get_bind())

    # ### end Alembic commands ###