"""adiciona tabela Produto

Revision ID: ef52012676f6
Revises: ef266295b881
Create Date: 2025-07-11 18:06:56.850301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef52012676f6'
down_revision: Union[str, Sequence[str], None] = 'ef266295b881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Produto', sa.String(), nullable=False),
    sa.Column('Link_Produto', sa.String(), nullable=False),
    sa.Column('Titulo', sa.String(), nullable=False),
    sa.Column('Descricao', sa.String(), nullable=False),
    sa.Column('Imagens', sa.String(), nullable=False),
    sa.Column('Baneficios', sa.String(), nullable=False),
    sa.Column('link_datasheet', sa.String(), nullable=False),
    sa.Column('Manual', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Produto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
